### ISSUE TITLE
Wallpaper set to lower than native res on HiDPI

### ISSUE THREAD

**Issue by rxfrxctxd** [Horus645/swww#22]
Hi, I've installed swww out of curiosity, and everything has been okay except the title of this issue.

I have noticed how wallpapers get set to a 1280x720 resolution (as reported by `swww query`)¹, even though my native res is 2560x1440 and so is the wallpaper's.
They look pixelated, same way that xwayland programs look due to scaling issues between `sway` trying to go for e.g 150% but x11 staying at 100%, giving it the same pixelated effect.

### Examples
![image](https://user-images.githubusercontent.com/104025732/187009282-322a86d0-a389-40c9-84b7-109ff6f8c64d.png)
![image](https://user-images.githubusercontent.com/104025732/187009296-91b65422-c16b-4ee3-a0fc-1b94e1d0e6b8.png)

### Additional context
I've compiled this program using Nix and made a [derivation](https://git.kirinsst.xyz/kir/kipkgs/src/branch/stream/pkgs/swww/swww.nix) for it, including a module and systemd service [here](https://git.kirinsst.xyz/kir/dotfiles/src/branch/stream/modules/users/graphical/wayland.nix) (line 394).
The systemd services successfully start, wallpaper gets set, so the binary works as well. If I set any random image as a wallpaper using e.g `swww img random.png`, it gets the same issue.

¹ `swww query` returns `eDP-1 = 1280x720, currently displaying: image: "bg3.png"`

### System info
Distro: NixOS (22.11.20220824.b784c5a)
WM: Sway
Device: ThinkPad T480
Display: QHD (2560x1440)
`swww -V`: swww 0.4.2

**Comment by Horus645** [comment]
Do other tools (e.g. `wlr-randr`) detect the resolution correctly? I am asking just to be sure.

I've a looked around quickly through sctk and found maybe one thing that could be related to this. Unfortunately, I am going to have to ask for your help testing it later, since my monitors aren't like that.

**Comment by Horus645** [comment]
> I am going to have to ask for your help testing it later

On that note, when/if you have the time, could you please try out PR 23 above to see if it fixes the issue?

**Comment by rxfrxctxd** [comment]
> Do other tools (e.g. `wlr-randr`) detect the resolution correctly? I am asking just to be sure.
Yes, wlr-randr reports it correctly as 2560x1440
![image](https://user-images.githubusercontent.com/104025732/187020989-a69d42b8-d619-49a0-a2bb-dcafebdeab9b.png)

### Unexpected results
> could you please try out PR 23 above to see if it fixes the issue?
Patching and building with PR 23, then running `swww init` gives this:
`Error: "Failed to connect to socket: Connection refused (os error 111)"`

I have fixed it by manually removing the socket under `/run/user/1000/swww.socket`, I am not sure why it stayed there, but maybe it was because of systemd services.

### [Protocol error while reading events]
A more important issue is that after removing the socket, and running `swww init`, I get `Error: "Socket file not found. Are you sure the daemon is running?"`
`swww init --no-daemon` reports `[wayland-client] Protocol error while reading events: Protocol error 1 on object wl_shm_pool@10: invalid width, height or stride (2560x1440, 10240)`

![image](https://user-images.githubusercontent.com/104025732/187022563-927f6174-f39a-46cf-83eb-d4098c1320af.png)

**Comment by Horus645** [comment]
Thank you for such detailed reports!

> I have fixed it by manually removing the socket under /run/user/1000/swww.socket

This seems to be related to #11. Ideally, something should be calling `swww kill` to kill the daemon, OR send it a `SIGTERM`. This will cause it to exit correctly, and remove the socket. If, for example, it receives a `SIGKILL`, there's nothing we can do, since that will force the daemon's immediate termination.

> [wayland-client] Protocol error while reading events: Protocol error 1 on object wl_shm_pool@10: invalid width, height or stride (2560x1440, 10240)

Sigh... this is what happens when you do things in a hurry. I forgot to multiply the the new `pool` size by the scale factor:

```rust
self.pool
//.resize(width as usize * height as usize * 4)
.resize(width as usize * height as usize * scale_factor as usize * 4)
.unwrap();
```

I wonder if there is a way of me mock testing this somehow. This is something I would have noticed immediately, but since my monitor's scale factor is '1', it didn't raise any errors :neutral_face:.

In any case, I am afraid I will have to ask you to test it again.

**Comment by Horus645** [comment]
UPDATE: that resize was STILL wrong, since the scale factor multiples both the width and height, we need to multiply it twice! Hopefully it is 100% fixed now.

**Comment by rxfrxctxd** [comment]
Tried with the newer patch, it compiles and initializing works, `swww query` even reports `eDP-1 = 2560x1440`, but...

### Wallpaper uncentered
For whatever reason, the wallpaper is kind of zoomed in and has an offset from the center, where instead of something like this:
![image](https://user-images.githubusercontent.com/104025732/187047073-a42bac66-a818-4c42-b680-3ca4cf54a9f5.png)

I get this:
![image](https://user-images.githubusercontent.com/104025732/187047124-1618ab5e-e030-4ef8-98dd-12389a61a6b9.png)

I unfortunately don't know Rust (yet..?), so can't help a lot on that part...

**Comment by Horus645** [comment]
Great news: turns out `wlr-randr` has a `--scale` flags that I somehow missed (sorry about that).

I can now test this on my, so I should be able to solve it soon:tm:

**Comment by rxfrxctxd** [comment]
If I from a native hidpi display do `wlr-randr --output eDP-1 --scale 1` then the wallpaper looks as it should, saying just in case

**Comment by Horus645** [comment]
Third time's the charm? Hopefully?

This time I managed to test it myself. I can confirm it is working on my end.

However, there is one problem: changing the scale factor after the image was sent will not resize it automatically. You will have to send in the image again.

I would rather fix this in a separate issue, since the workaround is very simple, unlike this problem, which doesn't have any workaround at all.

**Comment by rxfrxctxd** [comment]
Works on my end too, and can confirm that after changing the scaling factor the background becomes the default black.
I think this issue can be closed now.

**Comment by fedoranvar** [comment]
@rxfrxctxd could you please share your derivation ?

i'm trying to make derivation but i'm receiving errors in tests during build

```bash
   Compiling os_str_bytes v6.2.0
   Compiling adler v1.0.2
...skipping...
test daemon::processor::comp_decomp::tests::should_compress_and_decompress_to_same_info_with_equal_data ... ok
test daemon::processor::comp_decomp::tests::should_compress_and_decompress_to_same_info ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

     Running tests/integration_tests.rs (target/x86_64-unknown-linux-gnu/release/deps/integration_tests-a5d1608bd2d47977)
thread 'main' panicked at 'Unexpected failure.
code=1
stdout=""
stderr="Error: \"Failed to connect to socket: Connection refused (os error 111)\"\n"
', /build/rustc-1.64.0-src/library/core/src/ops/function.rs:248:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: test failed, to rerun pass '--test integration_tests'
```

**Comment by rxfrxctxd** [comment]
@fedoranvar My derivation lives [here](https://git.kirinsst.xyz/kir/kipkgs/src/branch/stream/pkgs/swww), although I had not updated it in a while. Look at the part of the deriv where I disabled tests, that's what gave me the socket error, which probably happens because of building through nix, somehow..

**Comment by fedoranvar** [comment]
for some reason i can't get access to this site, could you please paste this derivation temporary somewhere else?

**Comment by rxfrxctxd** [comment]
@fedoranvar Mirrored it here for now: https://github.com/rxfrxctxd/kipkgs/tree/stream/pkgs%2Fswww

Btw, what do you get when visiting my site from earlier? Would help fixing whatever that issue is.

**Comment by fedoranvar** [comment]
@rxfrxctxd 

thank you!succesfully builded package

i'm receiving timeout connection, maybe some restrictions from internet provider
